---
title: "Exercise2"
author: "yelu"
date: '2022-05-06'
output: github_document
---

```{r setup, echo = FALSE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

## R Markdown

```{r library,echo = TRUE, warning = FALSE, message = FALSE}
library(readr)        # to import tabular data (e.g. csv)
library(dplyr)        # to manipulate (tabular) data
library(ggplot2)      # to visualize data
library(sf)           # to handle spatial vector data
library(terra)        # To handle raster data
library(lubridate)    # To handle dates and times
```
## Tasks2 Data Import

```{r datainput,echo = TRUE, warning = FALSE, message = FALSE}
## Import the downloaded csv 
wildschwein_BE <- read_delim("wildschwein_BE_2056.csv",",") # adjust path
wildschwein_BE <- st_as_sf(wildschwein_BE, coords = c("E", "N"), crs = 2056, remove = FALSE)
```
## Tasks3 Data Overview

```{r overview,echo = TRUE, warning = FALSE, message = FALSE}
## Calculate time difference
wildschwein_BE$timelag  <- as.numeric(difftime(lead(wildschwein_BE$DatetimeUTC), wildschwein_BE$DatetimeUTC, units = "secs")) 
wildschwein_BE$timelag_it <- as.integer(difftime(lead(wildschwein_BE$DatetimeUTC), wildschwein_BE$DatetimeUTC, units = "secs"))

## How many individuals were tracked?
## For how long were the individual tracked? Are there gaps?
wildschwein_BE <- mutate(wildschwein_BE,timelag = as.numeric(difftime(lead(DatetimeUTC),DatetimeUTC)))
wildschwein_BE %>%
  group_by(TierID, TierName, CollarID) %>%
  summarise(         
    mean_timelag = mean(timelag, na.rm = T),
    total_timelag = sum(timelag, na.rm = T)
  )

## Were all individuals tracked concurrently or sequentially?
ggplot(wildschwein_BE,aes(DatetimeUTC,TierID,colour = TierID)) + geom_point()
## Date-Timelag plot
tl1 <- ggplot(wildschwein_BE,aes(DatetimeUTC,timelag,colour = TierID)) + geom_line()
tl1 +ylim(0,20000) + scale_x_datetime()

## ggplot(wildschwein_BE, aes(DatetimeUTC,colour = TierID)) + geom_histogram()

## Histogram plot of timelag
tl0 <- ggplot(wildschwein_BE, aes(x=timelag_it)) + geom_histogram()
tl0 + xlim(0,6000) + ylim(0,1500)

## Histogram of timelag for different objects
tl2 <- ggplot(wildschwein_BE, aes(x=timelag, colour=TierID)) +
  geom_histogram(fill="white",alpha=0.5, position="identity")
tl2 + xlim(0,15000) + ylim(0,15000)
## What is the temporal sampling interval between the locations?


```

## Tasks3 Deriving movement parameter: Speed

```{r Speed,echo = TRUE, warning = FALSE, message = FALSE}
wildschwein_BE <- wildschwein_BE %>%
  mutate(Elag = as.numeric((E - lead(E))),
         Nlag = as.numeric((N - lead(N))),
         steplength = as.numeric(sqrt((Elag^2 + Nlag^2))),
         speed = as.numeric((steplength/timelag))
  )
summary(wildschwein_BE$speed)

speed0 <- ggplot(wildschwein_BE,aes(DatetimeUTC,speed,colour = TierID)) + geom_line()
speed0 +ylim(0,1.5) + scale_x_datetime()

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Tasks4 Cross-scale movement analysis

```{r task4,echo = TRUE, warning = FALSE, message = FALSE}
## Import the downloaded csv 
caro <- read_delim("caro60.csv",",")
caro <- st_as_sf(caro, coords = c("E", "N"), crs = 2056, remove = FALSE)

caro <- caro %>%
mutate(
    timelag = as.numeric(difftime(lead(DatetimeUTC),DatetimeUTC)),
    Elag = as.numeric((E - lead(E))),
    Nlag = as.numeric((N - lead(N))),
    steplength = as.numeric(sqrt((Elag^2 + Nlag^2))),
    speed = as.numeric((steplength/timelag))
)

## Reducing the data
c3 <- seq.int(from = 1, to = 200, by = 3)
c6 <- seq.int(from = 1, to = 200, by = 6)
c9 <- seq.int(from = 1, to = 200, by = 9)

caro_3 <- caro %>% slice(c3)
caro_6 <- caro %>% slice(c6)
caro_9 <- caro %>% slice(c9)

caro_3 <- caro_3 %>%
mutate(
    timelag = as.numeric(difftime(lead(DatetimeUTC),DatetimeUTC)),
    Elag = as.numeric((E - lead(E))),
    Nlag = as.numeric((N - lead(N))),
    steplength = as.numeric(sqrt((Elag^2 + Nlag^2))),
    speed = as.numeric((steplength/timelag))
)

caro_6 <- caro_6 %>%
mutate(
    timelag = as.numeric(difftime(lead(DatetimeUTC),DatetimeUTC)),
    Elag = as.numeric((E - lead(E))),
    Nlag = as.numeric((N - lead(N))),
    steplength = as.numeric(sqrt((Elag^2 + Nlag^2))),
    speed = as.numeric((steplength/timelag))
)

caro_9 <- caro_9 %>%
mutate(
    timelag = as.numeric(difftime(lead(DatetimeUTC),DatetimeUTC)),
    Elag = as.numeric((E - lead(E))),
    Nlag = as.numeric((N - lead(N))),
    steplength = as.numeric(sqrt((Elag^2 + Nlag^2))),
    speed = as.numeric((steplength/timelag))
)

c3plot <- ggplot()+
  geom_path(
    data = caro_3,
    aes(x = E, y = N),
    color = 'blue'
    ) + 
  geom_path(
    data = caro,
    aes(x = E, y = N),
    color = 'red'
)
c6plot <- ggplot()+
  geom_path(
    data = caro_6,
    aes(x = E, y = N),
    color = 'grey'
    ) + 
  geom_path(
    data = caro,
    aes(x = E, y = N),
    color = 'red'
)
c9plot <- ggplot()+
  geom_path(
    data = caro_9,
    aes(x = E, y = N),
    color = 'green'
    ) + 
  geom_path(
    data = caro,
    aes(x = E, y = N),
    color = 'red'
)
c3plot
c6plot
c9plot

speed_plot <- ggplot()+
  geom_line(
    data = caro,
    aes(x = DatetimeUTC, y = speed),
    color = 'red'
    ) + 
  geom_line(
    data = caro_3,
    aes(x = DatetimeUTC, y = speed),
    color = 'blue'
    ) +
  geom_line(
    data = caro_6,
    aes(x = DatetimeUTC, y = speed),
    color = 'lightblue'
    ) +
  geom_line(
    data = caro_9,
    aes(x = DatetimeUTC, y = speed),
    color = 'khaki'
    )
speed_plot

```

## Tasks5 Tolling window functions
```{r task5,echo = TRUE, warning = FALSE, message = FALSE}
library(zoo)
window3 <- rollmean(caro$speed, k = 3, fill = NA, align = "left")
window4 <- rollmean(caro$speed, k = 4, fill = NA, align = "left")
window5 <- rollmean(caro$speed, k = 5, fill = NA, align = "left")
window6 <- rollmean(caro$speed, k = 6, fill = NA, align = "left")
window7 <- rollmean(caro$speed, k = 7, fill = NA, align = "left")
window8 <- rollmean(caro$speed, k = 8, fill = NA, align = "left")


par(mfrow = c(2, 3))
plot(window3)
plot(window4)
plot(window5)
plot(window6)
plot(window7)
plot(window8)

```
